### ISSUE TITLE
Add ability to override checks for certain mods

### ISSUE THREAD

**Issue by MagentaPuppy** [theRookieCoder/ferium#16]
For example, the latest release of [resolution control+](https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol) which is marked to be only 1.17 and hasn't updated in about a year still works on the latest version

**Comment by theRookieCoder** [comment]
This is the same problem as #12, there should be 'overrides' for certain checks that can be configured for every mod

**Comment by MagentaPuppy** [comment]
oops, sorry for missing that

**Comment by theRookieCoder** [comment]
No problem it's fine they're technically two seperate problem that can be solved in the same way

**Comment by theRookieCoder** [comment]
Fixed in 0475f7c6683d21bfc33ae8816cbcf8288e5b5193
For this specific issue, I'd disable the version check
