### ISSUE TITLE
Allow user added mods

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#17]
In commit ca6bcb70733625079e8c01665adf6e215f9819fe
"If there are files that are not the latest compatible version of a mod, then they are deleted. So _effectively_ the output directory is emptied"
I want to have an option to not empty the directory. Ex.
There are four mods
1. sodium
2. iris
3. c2me-fabric
4. resounding
Currently resounding is not a part of the profile therefore it deletes it.
I want it to keep resounding intact.
This is sorta-similar-but-not-very-similar to #12. I want to "overwrite the check"

**Comment by theRookieCoder** [comment]
This doesn't have anything to do with check overrides. This is an option for the entire profile, I'll just be adding this to the profile config.

**Comment by theRookieCoder** [comment]
Ok so I have considered this before, and I haven't done this because of one reason. How would I be able to tell apart file that you don't want to have deleted, and older versions of a mod that should be deleted? I genuinely have no idea which is why I hadn't implemented earlier. This is not a 'will not fix' in any way, I just have no idea what to do

**Comment by KyleUltimate** [comment]
Maybe do it by a file-by-file bases.
Ex.
I have
1. sodium 0.4.0
2. iris 1.2.2
3. c2me-fabric 0.2.0+alpha.6
4. dashloader 3.1.0
5. resounding(not in profile)
Sodium and dashloader aren't the newest, so ferium should detect them and update them.
But, let's say that the newest version of dashloder(3.1.1) has some problems, and I want to keep myself on this version.
Maybe a command smth like `lock-version`
`ferium lock-version dashloader`
And with resounding, because it's not in profile, it just doesn't change it.
This kind of behavior can be set in the config with smth like
`ferium ignore-not-profile-mods my profile`

**Comment by theRookieCoder** [comment]
The thing is, figuring out what the mod is from it's file name, hash, etc is really sketchy and might not consistently work. I have an idea, maybe directories should not be deleted when upgrading, and there will be a special directory called `extra` or something. After upgrading everything as usual, Ferium will just copy all the files in `output_directory/extra` to `output_directory`. That way you can add mods that are not on any mod distribution sites

**Comment by KyleUltimate** [comment]
I think a softlink(or a hardlink) would be better, otherwise, that would be a great solution to this problem!

**Comment by theRookieCoder** [comment]
If mod loaders follow symlinks, then I guess softlinking them would be fine!

**Comment by KyleUltimate** [comment]
hmm, in linux, fabric doesn't follow "soft" symlinks(The ones that you created via the `-s` option)
but it does follow "hard" symlink(The ones you create with no additional arguments)

**Comment by theRookieCoder** [comment]
Ah so if we're hardlinking, then we might as well copy the file right? Because the file names wouldn't stay the same afaik

**Comment by KyleUltimate** [comment]
yeah, I copying would be the better action here

**Comment by Nesewebel** [comment]
> How would I be able to tell apart a file that you _don't_ want to have deleted, and older versions of a mod that _should_ be deleted?

Maybe as a first step you could show a warning if the number of registered mods does not match the number of files in the directory, I didn't know that I had to backup my existing mods before using `ferium upgrade` and am still trying to figure out what I had installed before it got wiped.

It was my fault and now I know better, but it would still have helped to know beforehand that unregistered mods will be deleted.

Unrelated to the issue, but maybe something like `ferium undo` would also be nice (with a configurable backup directory that has all files from before an upgrade)

**Comment by theRookieCoder** [comment]
> I didn't know that I had to backup my existing mods before using ferium upgrade and am still trying to figure out what I had installed before it got wiped

I apologise for the inconvenience, it really isn't your fault! I only recently documented this behaviour, Ferium's output directory is not meant to be manually edited. I guess a 'fix' for this would be to check if the output directory has mods when the profile is created, and offer to create a backup if it does.

**Comment by theRookieCoder** [comment]
Another thing I thought of is instead of directly deleting the old/wrong files, we could move them to a directory and move that directory to the recycle bin or trash can after upgrading is finished

**Comment by theRookieCoder** [comment]
https://github.com/theRookieCoder/ferium/issues/33#issuecomment-1114706154
I'm planning to use [trash](https://crates.io/crates/trash) which is compliant with FreeDesktop Trash

**Comment by theRookieCoder** [comment]
Maybe instead of trash, we could just move old files to a `.old` directory in the output directory

**Comment by KyleUltimate** [comment]
.old?
Why do we need to hide it tho

**Comment by theRookieCoder** [comment]
The idea is that only people who really want to access those would see it

**Comment by KyleUltimate** [comment]
So, it's like a sort-of backup folder?

**Comment by theRookieCoder** [comment]
Yes, I really don't want any of [this](https://github.com/theRookieCoder/ferium/issues/17#issuecomment-1114320572) happening again

**Comment by theRookieCoder** [comment]
Fixed in 7d71d36714ee9e0bc6037e16e6eac1341e62da0f
Was much easier than I thought for some reason

**Comment by KyleUltimate** [comment]
hey, I've recently found out the symlink actually work!
I just set up the symlink incorrectly, I used releative path, but I sholud use absolute path instead.
It works when I use it.
