### ISSUE TITLE
Permission to add ferium to the AUR

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#19]
I already made a working PKGBUILD and desktop file.(Downloaded from the Github release)
I think it's more appropriate to first ask and then upload mine to the AUR.
PKGBUILD
```bash
# Maintainer: Kyle Shiue <shiue.kyle@gmail.com>
pkgname=ferium-bin
pkgver=3.20.1
pkgrel=1
pkgdesc="Ferium is an easy to use CLI program for downloading and updating Minecraft mods from Modrinth, CurseForge, and GitHub Releases."
arch=("x86_64")
url="https://github.com/theRookieCoder/ferium"
license=('MPL')
source=("https://github.com/theRookieCoder/ferium/releases/download/v$pkgver/ferium-linux-gnu.zip"
	"ferium.desktop")
md5sums=('SKIP'
	'SKIP')

package() {
	cd "$srcdir"
	install -Dm755 "ferium" "$pkgdir/usr/bin/ferium" 

	install -Dm644 -t "$pkgdir/usr/share/applications" ferium.desktop
}
```
Desktop file
```.desktop
[Desktop Entry]
Type=Application
Name=ferium
Comment=Ferium is an easy to use CLI program for downloading and updating Minecraft mods from Modrinth, CurseForge, and GitHub Releases.
Exec=/usr/bin/ferium
```

**Comment by theRookieCoder** [comment]
Thank you so much for doing this! I have no experience with uploading packages to package manager, but I'm a little nitpicky so here are a few things I noticed:
- The package name is `ferium-bin`, is this a convention? Would `ferium` be fine?
- The license is `MPL` but I usually put `MPL-2.0` so I think that would be more fitting, or is the license format different here?

**Comment by KyleUltimate** [comment]
1. Yes it must be `-bin`, since it's downloaded from github. If it's just ferium, it would be compiled from source.
2. Yep, I should've used MPL-2.0
3. It would be needed to add `Terminal=true`
4. I would also replace md5sums with sha256sums too.

**Comment by KyleUltimate** [comment]
@theRookieCoder 
https://aur.archlinux.org/packages/ferium-bin
This is the url!

**Comment by KyleUltimate** [comment]
Also one more thing.
You don't need any dependency to run this, correct?

**Comment by theRookieCoder** [comment]
Yup there are generally no runtime dependencies for Rust binaries because they're statically linked

**Comment by KyleUltimate** [comment]
hmm
this doesn't work in clean chroot
![image](https://user-images.githubusercontent.com/68589851/164960404-e89113f6-81f5-42a3-82b0-4185858e4ae2.png)

**Comment by KyleUltimate** [comment]
yep, after installing gtk3.
it worked
why would an cli application require gtk3?

**Comment by theRookieCoder** [comment]
The problem is the file dialog, there is actually a `gui` feature to disable this but it's enabled by default. The file dialog crate I use, [`rfd`](https://crates.io/crates/rfd), imports a bunch of bindings to GTK libraries so that is the problem. I think the best wait to do this would be to compile for both features in a GitHub Action. Then we can make the CLI version `ferium-bin` and the GUI file dialog version `ferium-bin-gui` or something

**Comment by KyleUltimate** [comment]
yep, I think that would be great

**Comment by theRookieCoder** [comment]
Yeah and adding GTK as a dependency for `ferium-bin-gui`. Also should it be `ferium-bin-gui` or `ferium-gui-bin`?

**Comment by theRookieCoder** [comment]
I've moved this to #20, we can discuss there
