### ISSUE TITLE
Crafty-Crashes does not download correctly

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#24]
If you disable both modloader and version check, it still doesn't work.
It seems like it downloads the wrong file.
https://github.com/Chocohead/Crafty-Crashes

**Comment by theRookieCoder** [comment]
There's nothing wrong with the compatibility checking, it's just the file which isn't being downloaded correctly. It's supposed to be 23kb but the one downloaded by Ferium is only 217 bytes

**Comment by KyleUltimate** [comment]
Oh ok, will do when i get home!

**Comment by KyleUltimate** [comment]
Added!

**Comment by KyleUltimate** [comment]
Can confirm it publishes perfectly!

**Comment by theRookieCoder** [comment]
I'm really happy with this workflow, thank you so much for publishing the AUR package and motivating me to automate the builds!
