### ISSUE TITLE
Please add Quilt Support

### ISSUE THREAD

**Issue by chrstffr** [theRookieCoder/ferium#25]
As Modrinth has started to support Quilt, I would love to see Quilt support in ferium as it at the moment downloads "the wrong version" of certain mods, like https://modrinth.com/mod/ok-zoomer
It can't find this mod either: https://modrinth.com/mod/qsl

**Comment by theRookieCoder** [comment]
Quilt support was added in `v3.22.0`, please update to the [latest version](https://github.com/theRookieCoder/ferium/releases/latest)

**Comment by chrstffr** [comment]
Awesome! Thank you! 👍

**Comment by theRookieCoder** [comment]
Oh and just an FYI, it will download Fabric mods too if it can't find a Quilt version. It will warn you though
