### ISSUE TITLE
Add dependencies when adding a mod

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#28]
As described in the title.
Also, it might be good to ask the user whether to download "optional" dependencies, which is the "suggest" field in fabric.mod.json and the forge and quilt equivalent

**Comment by theRookieCoder** [comment]
I think the best solution would be to add required dependencies when running `ferium add-<source>`, and ask if the user wants to add optional dependencies. That would work well with Modrinth, and I'll have to check for CurseForge. Is this necessary for GitHub Releases? Because digging into the mod manifest is not that worth it in my opinion, and how will we find the mod from its in-game mod_id?

**Comment by KyleUltimate** [comment]
I know you can get the mod_id from the mod manifest, but I don't think you can get it using only the API calls.
And for github releases, I don't that's strictly necessary, but it will be great to have it. Although I have no idea how to add it without manifest checking

**Comment by theRookieCoder** [comment]
Well it seems that dependencies are typically only specified for version and files. So would getting the latest file when adding the mod and dealing with the dependencies then be a good solution?

**Comment by KyleUltimate** [comment]
Maybe, you can add the newest dependency when the latest file is released. E.g.
1. REI v4.45 (updated on 2022/4/1)
2. Architectury API 1.30 (updated on 2022/3/28)
3. Architectury API 1.30.1 (updated on 2022/4/6)
ferium will get the 1.30 instead of the 1.30.1
Let's say next week REI updated to v4.46
1. REI v4.46 (updated on 2022/4/8)
2. 2. Architectury API 1.30 (updated on 2022/3/28)
3. Architectury API 1.30.1 (updated on 2022/4/6)
This time ferium will get 1.30.1

**Comment by KyleUltimate** [comment]
This could create a new type of problem tho, when two mods depends on the same mod, what version should it choose?
I personally think that when this type of problem happens, just choose the latest one possible between the two

**Comment by theRookieCoder** [comment]
I'm currently just adding the dependencies when the mod is being added to the config. The specific versions are being ignored for now. I guess this features can be updated once some sort of version override is added, but that would still have the problem you described

**Comment by theRookieCoder** [comment]
Fixed in `v3.23.0` b7c74b72467f9a2981c57a9513bcf3b912e88f42
