### ISSUE TITLE
Separate internals from CLI for usage as library

### ISSUE THREAD

**Issue by khionu** [theRookieCoder/ferium#3]
As on the can. This would allow people to build Ferium into other tools.

**Comment by theRookieCoder** [comment]
This is something I need to do to add GUI support

**Comment by theRookieCoder** [comment]
This will be a library crate, the repository is [here](https://github.com/theRookieCoder/libium). Ferium will use this library and the future GUI version of Ferium, [Gerium](https://github.com/theRookieCoder/gerium), will use `libium` too.

**Comment by khionu** [comment]
Why separate repos? Cargo explicitly supports having multiple binaries (though only one library) in the same project, without using a workspace.

**Comment by theRookieCoder** [comment]
I want Ferium and Gerium to be seperate projects

**Comment by theRookieCoder** [comment]
[Initial commit](https://github.com/theRookieCoder/libium/commit/4f30d98ca47eae0f6ce85492ba796eac8c85af01) complete. Only the config part of Ferium has been extracted (i.e. [`src/util/json.rs`](https://github.com/theRookieCoder/ferium/blob/main/src/util/json.rs)). I tested it by deleting `json.rs` from Ferium and using Libium it works fine

**Comment by theRookieCoder** [comment]
I've just added the launchermeta and miscellaneous parts to `libium`. I've basically removed the entire `util/` directory, the only files that remain in `src/` are `main.rs`, `error.rs`, and `cli.rs`, which are specific to the CLI program. The migration to `libium` will occure under the `libium-migration` branch

**Comment by theRookieCoder** [comment]
Done in #9

Check out [Libium](https://github.com/theRookieCoder/libium) for the library
