### ISSUE TITLE
Unable to delete a mod

### ISSUE THREAD

**Issue by DelofJ** [theRookieCoder/ferium#31]
When I try to remove a mod using the command "ferium remove", I get an error that says "invalid argument"
For example, if you try to remove a mod using the command "ferium remove Sodium" or "ferium remove "sodium-fabric-mc1.18.2-0.4.1+build.15.jar" (I don't know which one to use), you get the error "error: Found argument 'Sodium' which wasn't expected, or isn't valid in this context"

**Comment by theRookieCoder** [comment]
You should use `ferium remove`, you'll get an interface to select the mods to delete. If you really want to use the cli only, then you have to specify them in the option `--mod-names`. The mod names are options not arguments. Please read the documentation using `ferium remove --help`

**Comment by DelofJ** [comment]
Ok, sorry, it's just me who don't know who to use ferium 😅
Thanks
