### ISSUE TITLE
Offer to back up old mod files when creating a profile

### ISSUE THREAD

**Issue by theRookieCoder** [theRookieCoder/ferium#33]
A follow up to https://github.com/theRookieCoder/ferium/issues/17#issuecomment-1114320572 where a user got his previous mods wiped after using Ferium for the first time (`F`s in chat)

**Comment by KyleUltimate** [comment]
https://github.com/theRookieCoder/ferium/issues/17#issuecomment-1114569725
A possible solution for this is move the mods into the `extra` folder, since not all operating system has a recycle bin

**Comment by theRookieCoder** [comment]
Fixed by c19f6beab653bd97c50c3365f1f193426108b381
