### ISSUE TITLE
error decoding response body: invalid type: map, expected a string at line 1 column 915

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#35]
This is a problem when I try to add 
https://modrinth.com/mod/smooth-swapping
![image](https://user-images.githubusercontent.com/68589851/166449007-df4e8dac-9ef7-412c-89e4-054cb001cb63.png)

**Comment by theRookieCoder** [comment]
It seems like Ferinth's project struct doesn't have the correct type for moderator messages.
