### ISSUE TITLE
Add duplication of profiles

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#37]
Currently I have a profile for vanilla features
And I want to make a more create focused one.
So I created a new profile called "Tech"
One problem I found is that it seems to have no way of copying mods to another profile, so I have to painstakingly add every single mod hand by hand from the vanilla profile
Or you could copy the profile mods in config manually which is difficult for another reason. Because of all the profiles are in the same file, it's hard to copy mods with correct `{}`(I'm tempted to open another feature request of separating different versions of config into different file, but I'm not sure to open it in libium, or ferium)
So maybe add a command that can copy mods automatically?(including the ignore mod check in config to copy too)

**Comment by theRookieCoder** [comment]
I've had this problem myself actually! Would the ability to duplicate a profile be sufficient?

**Comment by KyleUltimate** [comment]
Yep, that would work as well, since I just have to modify the game version and or the modloader, which is very easy

**Comment by theRookieCoder** [comment]
Now I'm thinking adding an `--import` or `--duplicate` flag to the existing `profile create` command would be cleaner.

**Comment by theRookieCoder** [comment]
So I ended up adding a `--import` flag
Fixed by fe50731191f24265abe59f3421051dd42f93f687
