### ISSUE TITLE
Enhancement for the `remove` command

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#39]
In the current verison you have to use the `--mod-names` flag to straight up delete the mod from cli without using the interface.
I hope that an auto detect could be implemented.
What I mean is:
If i just type `ferium remove`, do what is currently implemented
But if I type `ferium remove Iris`, directly remove iris from the profile
This would save time in big modpacks

**Comment by theRookieCoder** [comment]
Miraculously it actually works! Added in 4c82445ea25b4f78f592c91631d6663f7a229dad
