### ISSUE TITLE
Wrong default mods directory on macOS

### ISSUE THREAD

**Issue by douira** [theRookieCoder/ferium#40]
Ferium uses `/Users/<user>/Library/ApplicationSupport/minecraft/mods` as the default mods directory as far as I can tell from my usage. This is wrong because the correct application support directory is `Application Support` (with a space). By default, the mod folder created by ferium isn't used since Minecraft lives in `/Users/<user>/Library/Application Support/minecraft` instead.

**Comment by theRookieCoder** [comment]
Actually `ApplicationSupport` is a shortcut or symlink to `Application Support`, so I don't know why it's not being used by Minecraft for you. I guess it would be better to use the actual directory anyways
