### ISSUE TITLE
Add documentation for where the config file is located.

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#43]
For Kane in Iris cord, he seems to struggle to find where the mod config is located.
![image](https://user-images.githubusercontent.com/68589851/166896683-e5e4abb0-0cac-4615-b026-e51cf4e75a68.png)

**Comment by theRookieCoder** [comment]
Yeah probably should do that. For reference, it follows the XDG config convention where the configs are located in `~/.config/<program_name>/` so Ferium's config is in `~/.config/ferium/config.json`. For the record, everything related to the config will always be in Libium (and it isn't third party!), admittedly Libium is only mentioned _way_ at the bottom of the README [here](https://github.com/theRookieCoder/ferium#building-from-source-or-working-with-ferium)

**Comment by theRookieCoder** [comment]
Fixed by db83f91db70d6e4cef63c00ac8018db1778c00d0
Also documented all the new featuers

**Comment by KyleUltimate** [comment]
I think windows and Mac os's config location should be documented too
Since for windows, I believe it would be even more difficult
I guess it's in %appdata%? I'm not sure tho

**Comment by theRookieCoder** [comment]
Nope the configs are always stored in `~/.config/ferium/config.json`, its a quite standard location so I don't think there would be much problems with it

**Comment by PockySweet** [comment]
I am unable to find the config file.
It would be really helpful to have a command which will print the location of it, as it seems like it wasnt created

**Comment by theRookieCoder** [comment]
If you're on *nix (macOS or Linux) the file is `$HOME/.config/ferium/config.json`. Entries beginning with `.` are hidden by default on Finder, Dolphin, Nautilus, etc. so you need to unhide them.

On Windows it's in `%USERPROFILE%\.config\ferium\config.json`. You can type that into Win+R to open it. Again explorer hides dot-directories by default so you'd need to unhide them to manually navigate to them.

The location is documented in https://github.com/gorilla-devs/ferium?tab=readme-ov-file#program-configuration. I don't know how useful a command to point to the config file would be.
