### ISSUE TITLE
Sort command improvement

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#45]
Currently the `sort` command sorts the mods using the alphabitcal order, but it sorts Captical letters first. E.g.
https://modrinth.com/mod/badpackets always get sorted last(unless there are other mods with not Capitcal letters in the first letter) even though it has `b` in the first letter.
I think this in intended, but I just think that just simply based on alphabetical order would be better for the user experience.

**Comment by theRookieCoder** [comment]
Actually had the exact same problem with `badpackets` too! I thought it was fine because there are very few mods whose names begin with lower case letters

**Comment by theRookieCoder** [comment]
Fixed by db83f91db70d6e4cef63c00ac8018db1778c00d0
