### ISSUE TITLE
Some GitHub Releases mods still fail to match

### ISSUE THREAD

**Issue by aschoettler** [theRookieCoder/ferium#47]
Here are a few mods I tried to download from github repositories which are not available on CurseForge. They all have 1.18.2 versions available but none of these were found by ferium. In each case, the version `1.18.2` appears in the title of the release, the filename of a jar file, or both.

- `senseiwells/ChunkDebug`
  - correct release is https://github.com/senseiwells/ChunkDebug/releases/tag/v1.0.2
  - release name is "ChunkDebug v1.0.2 for 1.16.5, 1.17.1, 1.18.1, and 1.18.2"
  - assets include `chunk-debug-1.18.2-1.0.2.jar`
- `Earthcomputer/clientcommands`
  - correct release is https://github.com/Earthcomputer/clientcommands/releases/tag/v2.6.6
  - release name is "Version 2.6.6 for Minecraft 1.18.2"
  - assets include `clientcommands-2.6.6.jar`
- `Coow/Cows-Odd-Widgets`
  - correct release is https://github.com/Coow/Cows-Odd-Widgets/releases/tag/v1.0.4
  - release name is "Release 1.0.4 for 1.18.2"
  - assets include `cows-odd-widgets-1.0.4.jar`
- `senseiwells/EssentialClient`
  - correct release is https://github.com/senseiwells/EssentialClient/releases/tag/v1.1.6
  - release name is "EssentialClient v1.1.6 for 1.16.5, 1.17.1, 1.18.1, and 1.18.2"
  - assets include `essential-client-1.18.2-1.1.6.jar`
- `Fallen-Breath/pca-protocol`
  - correct release is https://github.com/Fallen-Breath/pca-protocol/releases/tag/pca-protocol_v0.2.5
  - release name is "Fallen-Breath/pca-protocol"
  - assets include `pca-protocol-1.18.2-0.2.5.jar`
- `End-Tech/syncmatica`
  - correct release is https://github.com/End-Tech/syncmatica/releases/tag/v0.3.2-1.18.2
  - release name is "1.18.2 release 1.18.2"
  - assets include `syncmatica-1.18.2-0.3.2.jar`

**Comment by theRookieCoder** [comment]
Thank you so much! This will be very helpful for improving GitHub compatibility checking!

**Comment by KyleUltimate** [comment]
Well, I think the problem this user has is that it doesn't download the correct mod version. E.g.
In 1.18, If I disable both modloader and version check for syncmatica, It'll still download the 1.16.5 version of it.

**Comment by aschoettler** [comment]
Thank you for the response. As @KyleUltimate pointed out, disabling the mod loader check leads ferium to download an incorrect version for 3 of these 6 mods. For `senseiwells/EssentialClient`, `senseiwells/ChunkDebug`, and `End-Tech/syncmatica`, it found and downloaded the `1.16.5`-compatible file from the correct GH release where the release also lists the `1.18.2` jar file in the assets.

**Comment by theRookieCoder** [comment]
Ah I see, I apologise for the misunderstanding

**Comment by theRookieCoder** [comment]
Ah I figured it out, the problem is that the game version check also checks the release name. This wouldn't work very well when there are multiple versions in the same release. I guess we could just remove that check and make it more strict
