### ISSUE TITLE
Support for parallel upgrade checking

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#48]
Currently it takes a while to check all of the mods. I wonder would it be possible to seperate them into different threads.
Although would this hit the api limit more easily? Or does this not matter

**Comment by theRookieCoder** [comment]
I've wanted to do this for a while actually! I think the problem I encountered last time is that async threads might not be supported. I'll definitely have another go at it though, upgrading the mods does take way longer than I like

**Comment by KyleUltimate** [comment]
And if this is going to be implemented, I hope it's possible to specifiy the number of created threads in config too!
Just like pacman(But be like parallel upgrades)
![image](https://user-images.githubusercontent.com/68589851/167255970-f6c84566-c859-4da8-8498-8fa2abdee4ba.png)

**Comment by theRookieCoder** [comment]
Oh mah gawd its soooo fast I literally can't believe it. I'm so used to it taking ~1 second per mod but now it updates 44 mods in less than 5 seconds! Oh yeah and curseforge is giving me internal server errors 😅

**Comment by theRookieCoder** [comment]
14 seconds for getting the latest version and downloading 44 mods. Truly an insane improvement from the previous 200 seconds

**Comment by KyleUltimate** [comment]
14 seconds checking and downloading combined?
That's real damn fast
Can't wait to try it!

**Comment by theRookieCoder** [comment]
Hmmm might have just broken the CF API, I'm getting 404 `NoSuchBucket` errors from their API

**Comment by theRookieCoder** [comment]
Fixed by a3030158ee4b52c5aa8bad1806345cfe0c7a892d
**SPEEEEEED**

**Comment by theRookieCoder** [comment]
It's quite satisfying to upgrade now
