### ISSUE TITLE
Add support for CurseForge and Modrinth modpacks

### ISSUE THREAD

**Issue by theRookieCoder** [theRookieCoder/ferium#5]
The [CurseForge API](https://docs.curseforge.com) doesn't mention modpacks anywhere so we'll have to implement the modpack format, which is just a json file I believe. This might be why GDLauncher/MultiMC doesn't support modpacks, they aren't in the API

**Comment by theRookieCoder** [comment]
I realise now that modpacks have way more information than mods. They have resource packs, configs, mod configs, etc. If I wanted to add support for modpacks, it's not a 'mod manager' anymore. I'll consider it anyways

**Comment by DanSnow** [comment]
I made a [modpack downloader](https://github.com/DanSnow/minecraft-modpack-downloader) just for myself before. Hope this could be useful.

**Comment by theRookieCoder** [comment]
I'm currently considering just importing a modpack into a new profile in Ferium. It won't use the specific file in the manifest. Custom resource packs, configs, etc will just be copied to the `.minecraft` directory if a flag is specified when upgrading. What do you guys think? I've currently set the goal of getting Vanilla Enhanced [FABRIC] to work.

**Comment by mainrs** [comment]
> I realise now that modpacks have way more information than mods. They have resource packs, configs, mod configs, etc. If I wanted to add support for modpacks, it's not a 'mod manager' anymore. I'll consider it anyways

I did write a full-blown alternative to MultiMC in Rust + Tauri. Not sure if I still have it. I might have overwritten it when I installed Linux. If I find it I'll edit this post. I have low hopes though, pretty sure I didn't push it for some reason (and I regret it :) )

If you feel that way, then maybe it's a better idea to make separate project. You could for example convert this to a binary+library project. And the modpack manager can take advantage of the library.

It's up to you though. If you want to deal with modpacks you have to consider a lot of stuff. Something you should definitely think about early on is how to manage multiple MC versions. Or should another launcher take care of it (for example OG MC launcher). You could then simply create a new profile for that specific modpack.

**Comment by theRookieCoder** [comment]
I've already somewhat split this into a CLI frontend, Ferium, and a library backend, Libium. Th problem is I really can't find a good intuitive UI library for Rust. The only UI library I know is Flutter but the Flutter<->Rust interop tool doesn't really work for me.

**Comment by mainrs** [comment]
> The only UI framework I know is Flutter but the Flutter<->Rust interop tool doesn't really work for me. But I think making an mc launcher in Rust would be quite cool

There is Tauri. It's Electron but in Rust so to say. You write your "backend logic" in Rust and expose it through invocable commands. And these commands can be called from your UI. You can go the traditional route and use a web framework like React or Vue. Or you could opt for something like https://yew.rs/ if you want to stick to Rust-only.

**Comment by aschoettler** [comment]
The `itzg/docker-minecraft-server` repo has a server-side config option for easily setting up curseforge modpacks
https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-curseforge-modpack
Not sure if its helpful but just wanted to mention it.

**Comment by ImperatorStorm** [comment]
GTK works with Rust https://www.gtk.org/docs/language-bindings/rust/, and there are(possibly unmaintained) Qt bindings for Rust, https://github.com/rust-qt.

Web apps tend to be resource-hungry, while native toolkits, while possibly harder to use, typically use less(so long as you don't use the web part of them).
