### ISSUE TITLE
`429 Too Many Requests` when listing verbosely, then immediately upgrading a large number of mods

### ISSUE THREAD

**Issue by theRookieCoder** [theRookieCoder/ferium#51]
I tried to upgrade the top 100 mods on Modrinth and most failed with this error.

**Comment by theRookieCoder** [comment]
It only occures when I list verbose, then immediately upgrade

**Comment by theRookieCoder** [comment]
Possible fix would to have a 'network timeout' and stop spawning threads whenever this error is encountered

**Comment by theRookieCoder** [comment]
Hmm even if I wait for more than the specified time I'm being rate limited _again_

**Comment by theRookieCoder** [comment]
Simple solution: just let the user wait for the specified time. The error says how long there is till the rate limit is reset

**Comment by nebula-system** [comment]
This underlying issue, or the fix, is causing me problems trying to download a very long list of mods (400 or so). When attempting to download the list it consistently stops at 300 or so and says I've been rate limited, but then after waiting, the process gets to the same point and the same thing happens. so it can no longer finish the list. I'm resorting to using separate config files for portions of the list but it's very time-consuming and kind of defeats some of the benefits of using ferium compared to when my list was smaller.
