### ISSUE TITLE
Mod dependencies need to be checked between different mod sources as well

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#53]
![image](https://user-images.githubusercontent.com/68589851/167298983-f7b585b6-4445-4f04-9a95-657f39aeba24.png)
This happens, even if I do `ferium upgrade` two times.
And old sodium isn't in `.old` too.
It seems to always upgrade sodium no matter what.
This is a very strange problem, and I doubt anyone can recreate it

**Comment by KyleUltimate** [comment]
https://0x0.st/omZh.txt

**Comment by theRookieCoder** [comment]
Could you check and see if the file is named properly? It looks like the file's name is being changed. Could you watch when the file is being written?

**Comment by KyleUltimate** [comment]
Ah great found the root cause.
If you add both sodium from modrinth, and sodium from curseforge. This error will happen.
But I'm certain that I didn't add it from curseforge, so maybe some mods stated sodium as dependency, and ferium downloads it from curseforge too?

**Comment by KyleUltimate** [comment]
![image](https://user-images.githubusercontent.com/68589851/167299394-c394e042-73be-498a-a272-98edcec5dd29.png)

**Comment by theRookieCoder** [comment]
Maybe you downloaded sodium extra or reese's sodium options from a different source?

**Comment by theRookieCoder** [comment]
Ah where did you download Indigo from?

**Comment by KyleUltimate** [comment]
Also from modrinth...
Anyway this issue is resolved, but might be a potential issue for other users

**Comment by KyleUltimate** [comment]
Ah wait I got iris from curseforge that's prob where sodium came from

**Comment by theRookieCoder** [comment]
Yeah something like that, but Sodium isn't a hard dependency for Iris right?

**Comment by theRookieCoder** [comment]
Also [Iris](https://modrinth.com/mod/iris)

**Comment by KyleUltimate** [comment]
Interestingly, it is on curseforge.
https://www.curseforge.com/minecraft/mc-mods/irisshaders/relations/dependencies

> Yeah something like that, but Sodium isn't a hard dependency for Iris right?
