### ISSUE TITLE
Add a subcommand to search mod by fingerprint in Curseforge

### ISSUE THREAD

**Issue by baka-gourd** [theRookieCoder/ferium#55]
Algorithm：https://github.com/AndrewToaster/ForgedCurse/blob/main/ForgedCurse/Utility/MurmurrHash2.cs
Usage：https://github.com/baka-gourd/MinecraftModWatcher/blob/main/MinecraftModWatcher/Watcher.cs#L296
This can be done through the documentation to get the project information.

**Comment by theRookieCoder** [comment]
I've heard of fingerprints before but they're very poorly documented (https://docs.curseforge.com/#curseforge-core-api-fingerprints) and I still don't understand what they are. Is it just some sort of search API?

**Comment by baka-gourd** [comment]
Yes, the files in curseforge all have unique (at least I didn't find any duplicates) fingerprints, and you can use the fingerprint to get the project id, file id, slug and more

**Comment by baka-gourd** [comment]
My tool uses this api to convert non-curseforge modpacks to curseforge modpacks, thus automatically generating manifest to improve development efficiency

**Comment by baka-gourd** [comment]
Very similar, but using the curseforge special hash method.
[Modid](https://github.com/baka-gourd/MinecraftModWatcher/blob/main/MinecraftModWatcher/Response.cs#L31)
[Hash Algorithm](https://github.com/baka-gourd/MinecraftModWatcher/blob/main/MinecraftModWatcher/MurmurHash2.cs#L56)

**Comment by theRookieCoder** [comment]
Moved to #57
