### ISSUE TITLE
Add pre-installed mods to profile via reverse finding the project_id through mod file name

### ISSUE THREAD

**Issue by Rovetown** [theRookieCoder/ferium#56]
So I was wondering if it is possible in the Curseforge API to get the file names of downloadable mods on their website so you can get the project id from that mod.

With that you could make it so that with a command like `ferium reload` you scan through the mods folder, add these mods to the profile.
Then you can simply continue on with using ferium using your pre-installed mods without the use of the `user` folder.

**Comment by baka-gourd** [comment]
Practically duplicates #55

**Comment by theRookieCoder** [comment]
I think I'll merge both these issues into a new one

**Comment by theRookieCoder** [comment]
Moved to #57
