### ISSUE TITLE
A few issues & Improvements

### ISSUE THREAD

**Issue by Genious28** [theRookieCoder/ferium#62]
One question.. Where are the mods stored? 
Apparently, no matter what location i choose for my profile.. they're not located in the given folder. And even if i move the .exe file, it keeps the config (i.e; that how many and what profiles exist) Therefore, it must be saving the config file as well as the mods elsewhere, even after i delete the custom folder for mods it still says the profile and mods exist.

**Comment by theRookieCoder** [comment]
You seem to have misunderstood how Ferium works. The config simply stores _information_ about the profiles and what mods are configured for each profile. The config is just a json file, and nothing more. The mods will only be downloaded/upgraded when you run `ferium upgrade`.

And next time please use the [discussions](https://github.com/theRookieCoder/ferium/discussions) tab for questions!

**Comment by Genious28** [comment]
Alright, sorry.. Like i said on reddit, i have don't understand GitHub.

Btw, i got a bunch of suggestions; [here](https://github.com/theRookieCoder/ferium/issues/64#issue-1233871829)
