### ISSUE TITLE
Optional dependencies fail if already installed

### ISSUE THREAD

**Issue by ryanccn** [theRookieCoder/ferium#75]
There is a small problem in the installation of optional mod dependencies. I'm not a Rust developer myself, but the problem seems to be here:

https://github.com/theRookieCoder/ferium/blob/7e795a62e350b389846ce7d9c91bf0edbf5839bc/src/subcommands/add.rs#L139-L149

It should probably have the same error catching as this:

https://github.com/theRookieCoder/ferium/blob/7e795a62e350b389846ce7d9c91bf0edbf5839bc/src/subcommands/add.rs#L124-L130

**Comment by ryanccn** [comment]
(Same for both Modrinth and CurseForge)

**Comment by theRookieCoder** [comment]
Exactly what is the problem? Is it asking to add optional dependencies that have already been added?

**Comment by theRookieCoder** [comment]
I can't replicate this? For example Ok Zoomer has a required dependency QSL and an optional dependency Mod Menu. If QSL and Mod Menu are already installed, Ferium doesn't even ask if you want to add the optional dependency.

**Comment by theRookieCoder** [comment]
The code above checks if the dependency has alread been added, it only asks the user if it has not been added yet

**Comment by ryanccn** [comment]
<img width="770" alt="Screen Shot 2022-05-15 at 23 15 42" src="https://user-images.githubusercontent.com/70191398/168480137-3f453396-6d19-4711-bbda-c54df5562980.png">

**Comment by theRookieCoder** [comment]
<img width="1122" alt="Screenshot 2022-05-15 at 8 48 28 PM" src="https://user-images.githubusercontent.com/60034030/168480254-0814f9f7-68fd-47b6-a0d3-b7efccbe6cf7.png">
I cannot replicate.
I believe this might have been fixed in `v3.28.3`.

**Comment by ryanccn** [comment]
Indeed, the newest version worked. Thanks for the help!
