### ISSUE TITLE
Crates.io builds do not work

### ISSUE THREAD

**Issue by theRookieCoder** [theRookieCoder/ferium#80]
The reason is that the Libium version isn't locked in, so it auto updates to the latest version and doesn't compile anymore

**Comment by dtomvan** [comment]
Hello, I tried compiling ferium, and using `cargo b` works, but `cargo install --path .` doesn't.

**Comment by theRookieCoder** [comment]
What error do you get? Also you should probably use `just` rather than manually using cargo commands
